### ISSUE TITLE
Output Image Bounding Box

### ISSUE THREAD

**Issue by jwahnn** [jerpelhan/DAVE#13]
I am facing this weird issue where if I save the plot in lines 80-89 from demo.py as an image, it outputs an image with bounding boxes in some cases, but with repeated execution it sometimes outputs images with the bounding boxes being extremely small (more like a dot). Is this expected?

**Comment by jerpelhan** [comment]
Could you please clarify:
1. Did you change demo.py?
2. What do you mean by "repeated execution"? Running the ```python demo.py``` multiple times or?

**Comment by jwahnn** [comment]
1. I only added a line or two to demo.py, which is the part that saves the plot. It works fine now, but when I ran it yesterday, it outputted weird bounding boxes that are very small to the extent of looking like a dot for some reason. I cannot replicate the error right now, but all of my peers faced the same issue yesterday.
2. You are correct. Initially it was fine. After running the demo multiple times, it caused the issue described above.

Thanks for the quick response! I understand this is a weird issue, and I am confused too haha. I will look into the problem as well and update if I figure something out or if the problem is replicated.

In the meantime, let me know if you figure something out :)

**Comment by jerpelhan** [comment]
You might have accidentally clicked on the image, which resulted in a very small bounding box, resulting in those tiny dot-like predictions. Try printing out exemplar bounding box width and height if this problem persists.

**Comment by jwahnn** [comment]
Ah, this probably isn't the case because I am not using the functions that draw bounding boxes (btw these don't work so well as well). Instead, I use custom coordinates that I got from using other software tools, which I am very sure the resulting coordinates are not as small as a dot.

**Comment by jerpelhan** [comment]
The demo is designed for quick testing and is not the prettiest and ready for real usage :)  (you need to click and hold to draw the bounding box properly -- it works for many people who tested it). 

It looks like you changed more than just saving the image. Unfortunately, I can't help with that.

**Comment by jwahnn** [comment]
I'll update if I face the error again :)

All code that I added to the file was downloading the images and inserting the coordinate values for "bounding_box" myself, in which case I don't have to draw the boxes on the image.
