### ISSUE TITLE
require dataset preparation

### ISSUE THREAD

**Issue by facetohard** [jerpelhan/DAVE#17]
Could you release how to prepare your training dataset, I run the train_det.py and got the error: "not found nstances_val.json"

**Comment by jerpelhan** [comment]
You can find the download link for the dataset bounding box annotations at [Counting-DETR](https://github.com/VinAIResearch/Counting-DETR) repository.

**Comment by facetohard** [comment]
Thanks a lot!

**Comment by jerpelhan** [comment]
We wanted to share an update regarding this repository. We've developed a novel method, GeCo, which significantly outperforms the older approach in this repo by a large margin. You can check out the code and an easy-to-run demo here: https://github.com/jerpelhan/GeCo.
