### ISSUE TITLE
question about DAVE_3_shot_val.json

### ISSUE THREAD

**Issue by dearRongerr** [jerpelhan/DAVE#19]
I would like to express my appreciation for your work on this project. I have been going through the eval.py script and encountered an issue that I'm seeking guidance on.

When I attempted to run the eval.py, I received a FileNotFoundError with the following message:
> FileNotFoundError: [Errno 2] No such file or directory: '../DAVE_3_shot_val.json'

I'm unsure how to proceed to obtain the 'DAVE_3_shot_val.json' file, which seems to be missing from my local directory. Could you kindly provide me with some insight or instructions on how to acquire or generate this file?

Thank you in advance for your time and assistance. I look forward to your response.

**Comment by jerpelhan** [comment]
The DAVE_3_shot_val.json file is generated as part of the inference step on validation and test splits. The eval.py function only quantifies the quality of predicted bounding boxes. Here’s how to infer bounding boxes:

Run the Inference Script: DAVE/scripts/fscd_test.sh

This script should run the necessary inference steps and output JSON files, DAVE_3_shot_val.json, and  DAVE_3_shot_test.json.

**Comment by dearRongerr** [comment]
Thank you so much!That was really helpful.

**Comment by jerpelhan** [comment]
We wanted to share an update regarding this repository. We've developed a novel method, GeCo, which significantly outperforms the older approach in this repo by a large margin. You can check out the code and an easy-to-run demo here: https://github.com/jerpelhan/GeCo.
