### ISSUE TITLE
Whether there are plans to open source the training part of the code

### ISSUE THREAD

**Issue by hong-kailin** [jerpelhan/DAVE#2]
Whether there are plans to open source the training part of the code

**Comment by hong-kailin** [comment]
there are many bug in demo.py

**Comment by jerpelhan** [comment]
The training code is already available in the repository and involves two stages as described in the paper. First, use the pretrained LOCA model, then run `train_det.py`, followed by `train_sim.py`.

When reporting issues, could you please provide more details about the bugs? Did you run the code as specified in the README with the following command:
`python demo.py --skip_train --model_name DAVE_3_shot --backbone resnet50 --swav_backbone --reduction 8 --num_enc_layers 3 --num_dec_layers 3 --kernel_dim 3 --emb_dim 256 --num_objects 3 --num_workers 8 --use_query_pos_emb --use_objectness --use_appearance --batch_size 1 --pre_norm`

Please include any error messages you encounter so I can help you. Without this information, I can't provide the necessary support. Thank you!

**Comment by hong-kailin** [comment]
Thank you for your reply. It is a nice work!
I ran this program on a Windows 11 system.  
`python demo.py --skip_train --model_name DAVE_3_shot --backbone resnet50 --swav_backbone --reduction 8 --num_enc_layers 3 --num_dec_layers 3 --kernel_dim 3 --emb_dim 256 --num_objects 3 --num_workers 0 --use_query_pos_emb --use_objectness --use_appearance --batch_size 1 --pre_norm `

When I've finished drawing the 3 Bboxes, The program threw me an exception

>   File "D:\projects\DAVE\utils\data.py", line 16, in resize
>     scale_y = min(1.0, 50 / (bboxes[:, 3] - bboxes[:, 1]).mean())
>                              ~~~~~~^^^^^^
> IndexError: index 3 is out of bounds for dimension 1 with size 3

**Comment by jerpelhan** [comment]
Thank you, yes you are correct. I accidentally pushed the not most recent file, as I created the demo at the last minute for easy testing on arbitrary images. It was already updated and it should work.

**Comment by hong-kailin** [comment]
I have changed the code and got the correct result.  I can submit my changes.

**Comment by jerpelhan** [comment]
We wanted to share an update regarding this repository. We've developed a novel method, GeCo, which significantly outperforms the older approach in this repo by a large margin. You can check out the code and an easy-to-run demo here: https://github.com/jerpelhan/GeCo.
