### ISSUE TITLE
Issues After Following Appropriate Steps

### ISSUE THREAD

**Issue by jwahnn** [jerpelhan/DAVE#3]
I have followed the necessary steps, but the code seems to be bugging. Specifically, there are two more dependencies (matplotlib & pycocolib) that people should download. Then, they have to change the directories to the input file and training weights as well, as most of the files are currently under the material directory.

These are trivial, so people will figure them out, but the main issue is that even after all this I encounter the following error:

`    scale_x = min(1.0, 50 / (bboxes[:, 2] - bboxes[:, 0]).mean())`
`RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long`

**Comment by jerpelhan** [comment]
Thanks! So, in step 2, make sure to configure the dataset and model paths as indicated. The issues with the demo were updated just minutes ago, so it should now be working correctly. Please try again and let me know if you encounter any problems.

**Comment by jwahnn** [comment]
Thanks for the quick update!
If I am understanding correctly, do you mean that I have to have the entire dataset in the DAVE directory that I cloned?

**Comment by jerpelhan** [comment]
You do not need the dataset if you want to run only `demo.py`. For running other scripts, specify the data_path in `arg_parser.py` or in the script you run. The demo has been updated and should work.

**Comment by jwahnn** [comment]
Okay, so a few things:

The numbers in the bounding boxes must be a float type. This is, even if you have coordinates [1, 2, 3, 4], you need to write them in [1. , 2. , 3. , 4.] for the above error to not happen.

Even after this, I am still struggling with the following error, which I think has to do with Pillow image object not having the `.shape` attribute. Does the image type have to be specified or something?

    `scale_y` = (int(img.shape[1] * scale_y) // 8 * 8) / img.shape[1]
AttributeError: 'Image' object has no attribute 'shape'

**Comment by jerpelhan** [comment]
All the aforementioned issues were resolved with the last commit. Did you update your pulled code?

**Comment by jwahnn** [comment]
Ah, that makes more sense. Didn't know there were changes to the code. Thanks for the help :)
