### ISSUE TITLE
Error in dataset

### ISSUE THREAD

**Issue by cgc-cell** [jerpelhan/DAVE#4]
Hello!
When running train.py, An error occurred:
  File "/home/code/DAVE/train_det.py", line 200, in train
    `for img, bboxes, density_map, ids, scale_x, scale_y,_ in train_loader:`
RuntimeError: stack expects each tensor to be equal size, but got [1, 512, 304] at entry 0 and [1, 512, 512] at entry 1.
How to solve this problem?

**Comment by jerpelhan** [comment]
The issues should now be resolved. Before making the code public, I did some refactoring and merged multiple dataloaders, which led to this issue. When training DAVE, use the provided LOCA weights available in the [Google Drive](https://drive.google.com/drive/folders/10O4SB3Y380hcKPIK8Dt8biniVbdQ4dH4?usp=sharing) to avoid any issues.

**Comment by jerpelhan** [comment]
We wanted to share an update regarding this repository. We've developed a novel method, GeCo, which significantly outperforms the older approach in this repo by a large margin. You can check out the code and an easy-to-run demo here: https://github.com/jerpelhan/GeCo.
