### ISSUE TITLE
About "base_3_shot.pth" 

### ISSUE THREAD

**Issue by Erica-Yang** [jerpelhan/DAVE#8]
Hi, how to generate "base_3_shot.pth"? or is it the same as "loca_few_shot.pth" in LOCA?

**Comment by jerpelhan** [comment]
We replaced the MAX operation with a softmax operation in [LOCA](https://github.com/djukicn/loca/blob/main/models/loca.py) (lines 101-109) for more efficient training. You have two options: either train/use the original LOCA version and modify lines 338-348 in [dave.py](https://github.com/jerpelhan/DAVE/blob/master/models/dave.py) to match the original implementation in loca.py, or retrain the loca with the softmax operation/use weights base_3_shot.pth. Either way, the performance should be similar.

**Comment by Erica-Yang** [comment]
Thanks a lot for your reply!
